# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbabfb32b61b659476f37d85662fc215a11cf88cc3887a645eba61af73df6ad6b1285328b20b7a0cc29087543344e0946a2574ef6b41ed7e283abc787dc6152e

test:
  secret_key_base: c083987b4f2b4d5cea9f6a5b1a086ec55fc3cce4e74db1ecddac2503c39eacf1b2040c18da5e0e6820f3de2449ab48960bfeb608406e3cf5fe714f306ed6e886

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
